version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check for updates every week
    schedule:
      interval: 'weekly'
    # Add a label to pull requests
    labels:
      - 'dependencies'
    # Group all npm dependencies into a single pull request
    groups:
      npm-dependencies:
        patterns:
          - '*'
